###
GET http://localhost:3333/ HTTP/1.1

###
GET http://localhost:3333/astra HTTP/1.1


### REDIRECT
GET http://localhost:3333/r/5tUBbkPyyX8-a0R9 HTTP/1.1

### KEYS
GET http://localhost:3333/api/v1/keys/abbreviations HTTP/1.1

### ALL
GET http://localhost:3333/api/v1/abbreviations HTTP/1.1

### BY ID
GET http://localhost:3333/api/v1/abbreviations/16 HTTP/1.1

### CREATE
POST http://localhost:3333/api/v1/abbreviations HTTP/1.1
Content-Type: application/json

{
  "original_url": "https://www.google.com/?q=Express.js"
}

### TRASH
GET http://localhost:3333/api/v1/trash/abbreviations HTTP/1.1


